"""
============================================================
🦇 THE DARK KNIGHT OF PUBLIC HEALTH — EKT Feedback Round 2
============================================================
Emma Tsui's comments on Comprehensive Exams Final Draft

This file contains 46 comments extracted from:
  Schiller_Comprehensive_Exams_-_Final_Draft_for_review_EKT.docx

To integrate into your Batman PhD app (phd_app.py), you have two options:

  OPTION A: Import this data and bulk-insert into MongoDB
  OPTION B: Copy the EKT_FEEDBACK list into your existing comps data

Run this script standalone to insert into MongoDB, or import
EKT_FEEDBACK into your app code.
============================================================
"""

from datetime import datetime

# ─── Source metadata ───────────────────────────────────────
SOURCE_FILE = "Schiller_Comprehensive_Exams_-_Final_Draft_for_review_EKT.docx"
REVIEWER = "Emma Tsui"
REVIEW_DATE = "2025-06"  # Approximate date of review
FEEDBACK_ROUND = "EKT_Final_Draft"

# ─── Difficulty estimates (minutes) by comment type ────────
# Quick fix (typo, formatting, citation add): 5-10 min
# Clarification (reword a sentence/paragraph): 10-20 min
# Substantive (add content, restructure, find citations): 20-45 min
# Major (write new section, significant restructuring): 45-90 min

EKT_FEEDBACK = [
    # ══════════════════════════════════════════════════════
    # PAPER 1: HOME-BASED MEDICAL CARE (HBMC)
    # ══════════════════════════════════════════════════════
    {
        "id": "ekt2_01",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Overall Structure",
        "comment_id": 1,
        "reviewer": REVIEWER,
        "feedback": "Include a page of introduction to the exam overall that gives readers a sense of why these four topics, and what you are doing in each section (i.e., main goals of each section)",
        "action_type": "major",
        "estimated_minutes": 60,
        "status": "pending",
        "tags": ["structure", "intro", "cross-paper"],
        "priority": "high",
    },
    {
        "id": "ekt2_02",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Historical Context",
        "comment_id": 2,
        "reviewer": REVIEWER,
        "feedback": "Only focused on primary care...? (Clarify scope — is HBMC broader than primary care?)",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["scope", "definition"],
        "priority": "medium",
    },
    {
        "id": "ekt2_03",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Models of HBMC",
        "comment_id": 3,
        "reviewer": REVIEWER,
        "feedback": "Integrate figures and tables into the text (don't just reference them at the end)",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["formatting", "tables", "figures"],
        "priority": "medium",
    },
    {
        "id": "ekt2_04",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Models of HBMC",
        "comment_id": 4,
        "reviewer": REVIEWER,
        "feedback": "Put the HBMC models in the same order as they appear in Figure 1",
        "action_type": "quick_fix",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["ordering", "consistency"],
        "priority": "low",
    },
    {
        "id": "ekt2_05",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Models - Hospital at Home",
        "comment_id": 5,
        "reviewer": REVIEWER,
        "feedback": "Clarify: 'best suited' — does this mean HaH is best for older adults who HAVE experienced delirium/infections/falls, or best at helping them AVOID these outcomes?",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["clarity", "HaH"],
        "priority": "medium",
    },
    {
        "id": "ekt2_06",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "General",
        "comment_id": 6,
        "reviewer": REVIEWER,
        "feedback": "Check inconsistent spacing around commas throughout the entire document",
        "action_type": "quick_fix",
        "estimated_minutes": 20,
        "status": "pending",
        "tags": ["formatting", "commas", "cross-paper"],
        "priority": "low",
    },
    {
        "id": "ekt2_07",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Models - Home-Based Palliative Care",
        "comment_id": 7,
        "reviewer": REVIEWER,
        "feedback": "Clarify distinction between hospice and palliative care. Note that hospice typically focuses on patients likely to die within 6 months. Also define how 'severe illness' is determined in HBPaIC context.",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["definition", "hospice", "palliative"],
        "priority": "high",
    },
    {
        "id": "ekt2_08",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Economic Impact - LTSS",
        "comment_id": 8,
        "reviewer": REVIEWER,
        "feedback": "Add citations for LTSS economic claims (disability likelihood, cost estimates)",
        "action_type": "quick_fix",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["citations"],
        "priority": "high",
    },
    {
        "id": "ekt2_09",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Economic Impact - LTSS",
        "comment_id": 9,
        "reviewer": REVIEWER,
        "feedback": "Add citations AND clarify the logic: if most people pay out-of-pocket for LTSS, explain the mechanism by which costs get passed to public programs (e.g., spend-down to Medicaid eligibility)",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["citations", "logic", "Medicaid"],
        "priority": "high",
    },
    {
        "id": "ekt2_10",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Disadvantages - Clinical Limitations",
        "comment_id": 10,
        "reviewer": REVIEWER,
        "feedback": "Fix unclear phrasing: 'to care for' — reword for clarity",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["phrasing"],
        "priority": "low",
    },
    {
        "id": "ekt2_11",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Advantages - Health Outcomes",
        "comment_id": 11,
        "reviewer": REVIEWER,
        "feedback": "Given the 'Improves health outcomes' heading, need stronger evidence showing actual health outcome improvements (not just process changes like discontinuing medication)",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["evidence", "outcomes"],
        "priority": "high",
    },
    {
        "id": "ekt2_12",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Advantages - Cost Efficiency",
        "comment_id": 12,
        "reviewer": REVIEWER,
        "feedback": "Add a plain-language phrase explaining what the ICER measure means (US $117,300 per QALY) for readers unfamiliar with health economics",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["translation", "ICER", "accessibility"],
        "priority": "medium",
    },
    {
        "id": "ekt2_13",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Disadvantages - Supply Chain",
        "comment_id": 13,
        "reviewer": REVIEWER,
        "feedback": "Fix formatting: stray bullet point or indentation issue in supply chain section",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["formatting"],
        "priority": "low",
    },

    # ══════════════════════════════════════════════════════
    # GENERAL / CROSS-PAPER
    # ══════════════════════════════════════════════════════
    {
        "id": "ekt2_14",
        "paper": "General",
        "paper_num": 0,
        "section": "Formatting",
        "comment_id": 14,
        "reviewer": REVIEWER,
        "feedback": "Remove underlining throughout all four papers (use bold or italics instead where emphasis needed)",
        "action_type": "quick_fix",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["formatting", "underlining", "cross-paper"],
        "priority": "low",
    },

    # ══════════════════════════════════════════════════════
    # PAPER 2: CLIMATE DISASTERS & OLDER ADULTS
    # ══════════════════════════════════════════════════════
    {
        "id": "ekt2_16",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Introduction",
        "comment_id": 16,
        "reviewer": REVIEWER,
        "feedback": "Add source/citation (missing reference for a claim in the intro)",
        "action_type": "quick_fix",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["citations"],
        "priority": "medium",
    },
    {
        "id": "ekt2_17",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Successful Aging Theory",
        "comment_id": 17,
        "reviewer": REVIEWER,
        "feedback": "Was Successful Aging (SA) updated in light of the criticisms you describe? If not, explain how it remains relevant and useful for YOUR work despite its limitations",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["theory", "SA", "justification"],
        "priority": "high",
    },
    {
        "id": "ekt2_18",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Resilience Theory",
        "comment_id": 18,
        "reviewer": REVIEWER,
        "feedback": "Explain/unpack what 'positive aging' means — the term is used but not defined",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["definition", "positive aging"],
        "priority": "medium",
    },
    {
        "id": "ekt2_19",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Resilience Theory - Individual Level",
        "comment_id": 19,
        "reviewer": REVIEWER,
        "feedback": "TWO issues: (1) Add citation for claim that older adults have better emotional outcomes post-disaster. (2) Explain why individual level gets more detail than interpersonal and structural — or balance the discussion across all three.",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["citations", "balance", "resilience"],
        "priority": "high",
    },
    {
        "id": "ekt2_20",
        "paper": "Climate",
        "paper_num": 2,
        "section": "When Systems Fail",
        "comment_id": 20,
        "reviewer": REVIEWER,
        "feedback": "Make explicit connection between the 'systems failure' discussion and the resilience theory framework introduced earlier",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["connection", "theory"],
        "priority": "medium",
    },
    {
        "id": "ekt2_21",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Systems Theory / Socio-ecological Model",
        "comment_id": 21,
        "reviewer": REVIEWER,
        "feedback": "✅ 'Well explained' — POSITIVE FEEDBACK, no action needed",
        "action_type": "none",
        "estimated_minutes": 0,
        "status": "done",
        "tags": ["positive"],
        "priority": "none",
    },
    {
        "id": "ekt2_22",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Socioeconomic Factors",
        "comment_id": 22,
        "reviewer": REVIEWER,
        "feedback": "Clarify what 'First, the environmental...' refers to — the sentence/transition is unclear",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["clarity", "transition"],
        "priority": "medium",
    },
    {
        "id": "ekt2_23",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Mental Health Impacts",
        "comment_id": 23,
        "reviewer": REVIEWER,
        "feedback": "Clarify: when you say 'SDoH' may exacerbate risk, do you specifically mean existing systemic inequities? Be precise about which social determinants",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["SDoH", "precision"],
        "priority": "medium",
    },
    {
        "id": "ekt2_24",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Socioeconomic Factors",
        "comment_id": 24,
        "reviewer": REVIEWER,
        "feedback": "Define key resilience terms when first used: 'adaptive capacity', 'absorptive resilience' — explain their meanings, how they're measured, and how they relate/overlap",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["definitions", "resilience", "key terms"],
        "priority": "high",
    },
    {
        "id": "ekt2_25",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Socioeconomic Factors / Table",
        "comment_id": 25,
        "reviewer": REVIEWER,
        "feedback": "Also define 'transformative' resilience (appears in your table). Better explain how absorptive/adaptive/transformative concepts specifically help us understand older adults' responses to climate events",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["definitions", "resilience", "application"],
        "priority": "high",
    },
    {
        "id": "ekt2_26",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Existing Strategies",
        "comment_id": 26,
        "reviewer": REVIEWER,
        "feedback": "Missing content or unclear passage flagged with '?' — review and complete this section",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["missing", "incomplete"],
        "priority": "medium",
    },
    {
        "id": "ekt2_27",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Conclusion",
        "comment_id": 27,
        "reviewer": REVIEWER,
        "feedback": "DEFENSE PREP: Be ready to discuss what 'bridging sectors' (public health, housing, emergency mgmt) might look like concretely. Find or propose specific examples of cross-sector systems.",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["defense_prep", "examples", "cross-sector"],
        "priority": "medium",
    },
    {
        "id": "ekt2_28",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Appendix - Table 1 (Resilience Theory)",
        "comment_id": 28,
        "reviewer": REVIEWER,
        "feedback": "Did you adapt or create this framework/table? If so, state that explicitly in the text (e.g., 'Drawing on Windle, Holt-Lunstad, and Netuveli & Blane, I organize resilience into three categories...')",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["attribution", "framework"],
        "priority": "medium",
    },
    {
        "id": "ekt2_29",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Appendix - Table 2 (Socio-Ecological Levels)",
        "comment_id": 29,
        "reviewer": REVIEWER,
        "feedback": "Same as above: clarify in the text whether you created/adapted this table synthesizing system levels with resilience domains, and describe your process",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["attribution", "framework"],
        "priority": "medium",
    },
    {
        "id": "ekt2_30",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Appendix",
        "comment_id": 30,
        "reviewer": REVIEWER,
        "feedback": "Fix table numbering: the climate stressors × geriatric syndromes table should be Table 3 (not Table 2 again)",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["numbering"],
        "priority": "low",
    },
    {
        "id": "ekt2_31",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Appendix",
        "comment_id": 31,
        "reviewer": REVIEWER,
        "feedback": "Fix table numbering: the U.S. disasters 2017-2025 table should be Table 4 (not Table 3)",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["numbering"],
        "priority": "low",
    },

    # ══════════════════════════════════════════════════════
    # PAPER 3: DELPHI METHOD
    # ══════════════════════════════════════════════════════
    {
        "id": "ekt2_33",
        "paper": "Delphi",
        "paper_num": 3,
        "section": "Overview of the Delphi Method",
        "comment_id": 33,
        "reviewer": REVIEWER,
        "feedback": "Remove duplicated content: Section III repeats the four core features already described in Section II. Cut the redundancy.",
        "action_type": "quick_fix",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["redundancy", "cut"],
        "priority": "medium",
    },
    {
        "id": "ekt2_34",
        "paper": "Delphi",
        "paper_num": 3,
        "section": "Overview - Definition of Expertise",
        "comment_id": 34,
        "reviewer": REVIEWER,
        "feedback": "IMPORTANT: Integrate a discussion of how 'expertise' is defined (and its range of definitions) EARLIER in the paper, not just as a passing note. This is especially important since your proposed HBMC Delphi includes 'lived experience experts' (patients, caregivers) alongside clinical experts.",
        "action_type": "major",
        "estimated_minutes": 45,
        "status": "pending",
        "tags": ["expertise", "definition", "restructure"],
        "priority": "high",
    },
    {
        "id": "ekt2_35",
        "paper": "Delphi",
        "paper_num": 3,
        "section": "Variations of the Delphi Method",
        "comment_id": 35,
        "reviewer": REVIEWER,
        "feedback": "Do different Delphi variations treat expertise and the kinds of experts involved differently? For example, does 'Decision Delphi' ever include lived experience experts, or only decision-makers?",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["expertise", "variations"],
        "priority": "medium",
    },
    {
        "id": "ekt2_36",
        "paper": "Delphi",
        "paper_num": 3,
        "section": "Applications - HEPI Tool",
        "comment_id": 36,
        "reviewer": REVIEWER,
        "feedback": "Are the indicators/tools resulting from these Delphi studies now actually being used by practitioners? Comment on uptake/implementation. Also address practicality concerns — is a 51-item tool feasible?",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["implementation", "practicality"],
        "priority": "medium",
    },
    {
        "id": "ekt2_37",
        "paper": "Delphi",
        "paper_num": 3,
        "section": "Synthesis",
        "comment_id": 37,
        "reviewer": REVIEWER,
        "feedback": "✅ 'Yes agree' — POSITIVE FEEDBACK, no action needed",
        "action_type": "none",
        "estimated_minutes": 0,
        "status": "done",
        "tags": ["positive"],
        "priority": "none",
    },

    # ══════════════════════════════════════════════════════
    # PAPER 4: SUBNATIONAL COMPARATIVE POLICY ANALYSIS (SCPA)
    # ══════════════════════════════════════════════════════
    {
        "id": "ekt2_39",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Introduction",
        "comment_id": 39,
        "reviewer": REVIEWER,
        "feedback": "Grammar fix: 'but responsibility' — check phrasing (likely should be 'but responsibility for administration...')",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["grammar"],
        "priority": "low",
    },
    {
        "id": "ekt2_40",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Introduction",
        "comment_id": 40,
        "reviewer": REVIEWER,
        "feedback": "You introduce 'conjunctural causation' and 'equifinality' in the intro but don't explain them until later. Either add brief definitions here or signal that they'll be explained in Section 3.3.",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["definitions", "forward reference"],
        "priority": "medium",
    },
    {
        "id": "ekt2_41",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Origins - Behavioralism Critique",
        "comment_id": 41,
        "reviewer": REVIEWER,
        "feedback": "Add a concrete example of how behavioralist approaches treat policy variations as anomalies rather than distinct causal processes",
        "action_type": "substantive",
        "estimated_minutes": 20,
        "status": "pending",
        "tags": ["example", "behavioralism"],
        "priority": "medium",
    },
    {
        "id": "ekt2_42",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "SCPA Design - Scaling Down",
        "comment_id": 42,
        "reviewer": REVIEWER,
        "feedback": "How does CPA handle choosing or sampling comparators once one has decided to 'scale down'? Address the practical question of case selection when you can't include all 50 states.",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["case selection", "methodology"],
        "priority": "high",
    },
    {
        "id": "ekt2_43",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "SCPA Design - Scaling Down",
        "comment_id": 43,
        "reviewer": REVIEWER,
        "feedback": "Does CPA case selection relate to the broader qualitative practice of purposive sampling? Or is it methodologically distinct? Draw this connection.",
        "action_type": "clarification",
        "estimated_minutes": 15,
        "status": "pending",
        "tags": ["purposive sampling", "methodology"],
        "priority": "medium",
    },
    {
        "id": "ekt2_44",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "SCPA Design - Controlled Comparisons",
        "comment_id": 44,
        "reviewer": REVIEWER,
        "feedback": "Introduce Galton's problem BEFORE you mention it — currently it appears without context. Add a brief definition/explanation before the first reference.",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["ordering", "definition", "Galton"],
        "priority": "medium",
    },
    {
        "id": "ekt2_45",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Causal Complexity",
        "comment_id": 45,
        "reviewer": REVIEWER,
        "feedback": "Add a signpost/transition sentence before introducing QCA — it currently 'comes out of nowhere.' Something like: 'To operationalize this configurational logic, researchers have developed Qualitative Comparative Analysis (QCA)...'",
        "action_type": "clarification",
        "estimated_minutes": 10,
        "status": "pending",
        "tags": ["transition", "QCA"],
        "priority": "medium",
    },
    {
        "id": "ekt2_46",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Causal Complexity - Bounded Scope",
        "comment_id": 46,
        "reviewer": REVIEWER,
        "feedback": "Related to bounded scope discussion: what about the qualitative concept of 'transferability' of findings (under particular conditions)? Is this relevant to CPA? Consider connecting.",
        "action_type": "substantive",
        "estimated_minutes": 20,
        "status": "pending",
        "tags": ["transferability", "qualitative", "theory"],
        "priority": "medium",
    },
    {
        "id": "ekt2_47",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Implications for HBMC",
        "comment_id": 47,
        "reviewer": REVIEWER,
        "feedback": "Figures on configurational causation are helpful, but HOW does someone actually do this in practice? Discuss specific approaches to sampling, data collection, and analysis that would be needed.",
        "action_type": "substantive",
        "estimated_minutes": 30,
        "status": "pending",
        "tags": ["methodology", "practical", "how-to"],
        "priority": "high",
    },
    {
        "id": "ekt2_48",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Implications - Internal Variation",
        "comment_id": 48,
        "reviewer": REVIEWER,
        "feedback": "You note that states aren't internally coherent (urban vs rural preparedness varies). So how does SCPA handle this? What strategies exist for dealing with within-state variation?",
        "action_type": "substantive",
        "estimated_minutes": 25,
        "status": "pending",
        "tags": ["within-state", "methodology"],
        "priority": "high",
    },
    {
        "id": "ekt2_49",
        "paper": "SCPA",
        "paper_num": 4,
        "section": "Implications - Variation Under Shared Framework",
        "comment_id": 49,
        "reviewer": REVIEWER,
        "feedback": "Decentralized governance isn't the only factor — also note: variations in disaster types faced, other state-level policy choices, available resources, historical context, political culture, etc.",
        "action_type": "substantive",
        "estimated_minutes": 20,
        "status": "pending",
        "tags": ["context", "additional factors"],
        "priority": "medium",
    },
]

# Also capture the 2 inline marked text issues from the document
INLINE_MARKS = [
    {
        "id": "ekt2_mark_01",
        "paper": "HBMC",
        "paper_num": 1,
        "section": "Models of HBMC",
        "comment_id": None,
        "reviewer": REVIEWER,
        "feedback": "Fix repeated text: 'on the other, on the other' — remove duplicate phrase",
        "action_type": "quick_fix",
        "estimated_minutes": 2,
        "status": "pending",
        "tags": ["typo", "duplicate"],
        "priority": "low",
    },
    {
        "id": "ekt2_mark_02",
        "paper": "Climate",
        "paper_num": 2,
        "section": "Socioeconomic Factors",
        "comment_id": None,
        "reviewer": REVIEWER,
        "feedback": "Fix highlighted text: 'First, the environmental' — incomplete/unclear sentence start",
        "action_type": "quick_fix",
        "estimated_minutes": 5,
        "status": "pending",
        "tags": ["phrasing", "incomplete"],
        "priority": "low",
    },
]

# Combine all feedback
ALL_FEEDBACK = EKT_FEEDBACK + INLINE_MARKS


def insert_to_mongodb(username: str, password: str, host: str = "cluster.reykijw.mongodb.net", db_name: str = "phd_app"):
    from pymongo import MongoClient
    client = MongoClient(
        f"mongodb+srv://{host}/?appName=Cluster",
        username=username,
        password=password,
        tls=True,
        tlsAllowInvalidCertificates=True,
    )
    db = client[db_name]
    collection = db["comps_feedback"]

    docs = []
    for item in ALL_FEEDBACK:
        doc = {
            **item,
            "source_file": SOURCE_FILE,
            "feedback_round": FEEDBACK_ROUND,
            "created_at": datetime.utcnow(),
            "completed_at": None,
            "notes": "",
        }
        docs.append(doc)

    for doc in docs:
        collection.update_one({"id": doc["id"]}, {"$set": doc}, upsert=True)

    print(f"✅ Inserted/updated {len(docs)} feedback items into '{db_name}.comps_feedback'")
    client.close()


if __name__ == "__main__":
    insert_to_mongodb(
        username="gschiller94_db_user",
        password="Dgerito2027",
    )
